### ISSUE TITLE
Novice's help can not be compiled

### ISSUE THREAD

**Issue by 3038922** [OkapiLib/OkapiLib-legacy#1]
PC -I../include -I../src auto.cpp
~/gcc-arm-none-eabi-4_9-2014q4/bin/arm-none-eabi-g++ -I../include -I../src -c -Wall -pedantic -Wextra -Wconversion -Wno-implicit-fallthrough -Wmissing-include-dirs -mthumb -mcpu=cortex-m3 -mlittle-endian -mfloat-abi=soft -O2
-ffunction-sections -fsigned-char -fomit-frame-pointer -fsingle-precision-constant -std=c++14 -fno-exceptions -fno-rtti -felide-constructors -o ../bin/_bin_auto.o auto.cpp
/bin/sh: /home/aresp/gcc-arm-none-eabi-4_9-2014q4/bin/arm-none-eabi-g++: No such file or directory
make[1]: *** [Makefile:50: ../bin/auto.o] Error 127
make: *** [Makefile:52: src] Error 2

**Comment by Octogonapus** [comment]
I am going to assume you are on Linux (I basically only support Linux rn as all my time is going into making OkapiLib for PROS 3). You need to download the arm-none-eabi toolchain and whatever other packages Ubuntu wants, so run:
```
sudo apt-get update -y
sudo apt-get install -y lib32z1 lib32ncurses5 lib32bz2-1.0
wget -O ~/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2 https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2
tar -xf ~/gcc-arm-none-eabi-4_9-2014q4-20141203-linux.tar.bz2 -C ~
```
